Neos:
  Flow:
    http:
      chain:
        preprocess:
          chain:
            cors:
              position: start
              component: Netlogix\Cors\Http\Component\CorsComponent
              componentOptions:
                allowedMethods:
                  - GET
                allowedOrigins: {  }
                allowedHeaders: {  }
                allowCredentials: false
